apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      component: server
  replicas: 1
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: mphclub-api
          image: 077003688714.dkr.ecr.us-east-1.amazonaws.com/mphclub_api:latest
          ports:
            - containerPort: 8080
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: aws_secret_key
            - name: COGNITO_USER_POOL_ID
              value: us-east-1_VlDwxHvwj
            - name: PGUSER
              value: mphclub
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: mphclub
            - name: PGPASSWORD
              value: mphclub123
            - name: AWS_BUCKET
              value: mphclub
            - name: APP_ENV
              value: development
      imagePullSecrets:
        - name: awsecr-cred
