apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mphclub.biz
      http:
        paths:
          - path: /api/
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 8080
    - host: admin.mphclub.biz
      http:
        paths:
          - path: /api/
            backend:
              serviceName: cs-portal-cluster-ip-service
              servicePort: 8081
